- hosts: ansible-terraform
  tasks:
  - name: Instalando python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      - git
      update_cache: yes # Sempre manter atualizado o projeto
    become: yes # Usar sudo
    
  - name: Instalando as dependencias do projeto FAST-API
    pip:
       virtualenv: /home/ubuntu/app/venv
       name:
       - "uvicorn[standard]"
       - fastapi
       - pydantic
     
  - name: Clone do projeto no GIT
    git:
      repo: https://github.com/GustavoHBraga/Produtos-api
      dest: /home/ubuntu/app/project
      clone: yes
      force: yes
     
  - name: Iniciando o projeto FAST API
    ansible.builtin.shell:
      cmd: '. /home/ubuntu/app/venv/bin/activate; python /home/ubuntu/app/project/app.py'
    async: 3500
    poll: 0
    
    